// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRm5ktgie79IFExzPqGvldQjtxBF21L7Q',
    appId: '1:866983687701:android:60504bf578b45bb357c01c',
    messagingSenderId: '866983687701',
    projectId: 'seniorcareapp-66a1f',
    storageBucket: 'seniorcareapp-66a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4wU4i8UPI8waxxn_WQCpg0LC8_mVqbq8',
    appId: '1:866983687701:ios:0129ecade46d3e9057c01c',
    messagingSenderId: '866983687701',
    projectId: 'seniorcareapp-66a1f',
    storageBucket: 'seniorcareapp-66a1f.firebasestorage.app',
    androidClientId: '866983687701-prj5eq3vs3g95tf2j3q4b6js86kukmun.apps.googleusercontent.com',
    iosClientId: '866983687701-elqciln6j3ed598k5rnktbtpb58htej1.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorCareApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE8MYyKOg2rN4oVm6P6xjGo2bndojO-7E',
    appId: '1:866983687701:web:9ea431fe89550af357c01c',
    messagingSenderId: '866983687701',
    projectId: 'seniorcareapp-66a1f',
    authDomain: 'seniorcareapp-66a1f.firebaseapp.com',
    storageBucket: 'seniorcareapp-66a1f.firebasestorage.app',
    measurementId: 'G-RY70JP68FJ',
  );

}